# Generated by Django 4.2.14 on 2024-09-12 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.IntegerField()),
                ('myhomelink', models.URLField()),
                ('myhomeid', models.IntegerField()),
                ('sslink', models.URLField()),
                ('ssid', models.IntegerField()),
                ('area', models.IntegerField()),
                ('price', models.IntegerField()),
                ('percent', models.IntegerField()),
                ('address', models.TextField()),
                ('limitations', models.TextField()),
                ('agent', models.TextField()),
            ],
        ),
    ]
