# Generated by Django 4.2.15 on 2024-09-13 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_forrent_forsale_delete_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ForRent',
        ),
        migrations.DeleteModel(
            name='ForSale',
        ),
    ]
