# Generated by Django 4.2.15 on 2024-09-13 08:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('content', '0004_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergroup',
            name='user_selection',
            field=models.ManyToManyField(blank=True, related_name='selected_groups', to=settings.AUTH_USER_MODEL),
        ),
    ]
