# Generated by Django 4.2.15 on 2024-09-13 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_usergroup_user_selection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usergroup',
            name='user_selection',
        ),
    ]
