# Generated by Django 4.2.15 on 2024-09-13 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_remove_usergroup_user_selection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forsale',
            name='group',
        ),
        migrations.RemoveField(
            model_name='usergroup',
            name='leader',
        ),
        migrations.RemoveField(
            model_name='usergroup',
            name='members',
        ),
        migrations.DeleteModel(
            name='ForRent',
        ),
        migrations.DeleteModel(
            name='ForSale',
        ),
        migrations.DeleteModel(
            name='UserGroup',
        ),
    ]
