# Generated by Django 4.2.15 on 2024-09-13 08:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('content', '0007_remove_forsale_group_remove_usergroup_leader_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='led_groups', to=settings.AUTH_USER_MODEL)),
                ('members', models.ManyToManyField(related_name='user_groups', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ForSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.IntegerField()),
                ('myhomelink', models.URLField()),
                ('myhomeid', models.IntegerField()),
                ('sslink', models.URLField()),
                ('ssid', models.IntegerField()),
                ('area', models.IntegerField()),
                ('price', models.IntegerField()),
                ('percentage', models.IntegerField()),
                ('address', models.TextField()),
                ('agent', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale_posts', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sale_ads', to='content.usergroup')),
            ],
        ),
        migrations.CreateModel(
            name='ForRent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.IntegerField()),
                ('myhomelink', models.URLField()),
                ('myhomeid', models.IntegerField()),
                ('sslink', models.URLField()),
                ('ssid', models.IntegerField()),
                ('area', models.IntegerField()),
                ('price', models.IntegerField()),
                ('address', models.TextField()),
                ('limitations', models.TextField()),
                ('agent', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rent_posts', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rent_ads', to='content.usergroup')),
            ],
        ),
    ]
